site_name: Cooper DBW Good Book
theme:
  logo: assets/CU_Logo.png
  name: material
  palette:
    accent: red
    primary: red
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
